meme_examples = [
    {"caption": "Always has been", "image": "always_has_been.png", "context_tags": ["gotcha", "reveal"]},
    {"caption": "Ancient aliens", "image": "ancient_aliens.png", "context_tags": ["wild-idea", "conspiracy"]},
    {"caption": "Applying clown makeup", "image": "applying_clown_makeup.png", "context_tags": ["bad-decision", "self-mockery"]},
    {"caption": "Batman slaps Robin", "image": "batman_slap_robin.png", "context_tags": ["rejection", "shut-down"]},
    {"caption": "Bernie asking again", "image": "bernie_asking.png", "context_tags": ["persistence", "request"]},
    {"caption": "Bike fall", "image": "bike_fall.png", "context_tags": ["self-sabotage", "bad-decision"]},
    {"caption": "Boardroom suggestion", "image": "boardroom_meeting_suggestion.png", "context_tags": ["dismissal", "bad-idea"]},
    {"caption": "Buff Doge vs Cheems", "image": "buffdoge_vs_cheems.png", "context_tags": ["comparison", "contrast"]},
    {"caption": "Bugs No", "image": "bugs_no.png", "context_tags": ["denial", "rejection"]},
    {"caption": "Button slap instantly", "image": "button_slap_instantly.png", "context_tags": ["impulsive", "quick-decision"]},
    {"caption": "Change my mind", "image": "change_my_mind.png", "context_tags": ["debate", "opinion"]},
    {"caption": "Drake Yes/No", "image": "drake_yesno.png", "context_tags": ["preference", "choice"]},
    {"caption": "Evil Kermit", "image": "evil_kermit.png", "context_tags": ["temptation", "bad-advice"]},
    {"caption": "Expanding brain", "image": "expanding_brain.png", "context_tags": ["evolution", "smart-idea"]},
    {"caption": "Fairly oddparents trophy", "image": "fairlyoddparents_trophy.png", "context_tags": ["mock-award", "sarcasm"]},
    {"caption": "Futurama Fry", "image": "futurama_fry.png", "context_tags": ["skeptical", "uncertain"]},
    {"caption": "Gigachad", "image": "gigachad.png", "context_tags": ["confidence", "dominance"]},
    {"caption": "Grus Plan", "image": "grus_plan.png", "context_tags": ["unexpected", "twist"]},
    {"caption": "Hide the pain Harold", "image": "hide_the_pain_harold.png", "context_tags": ["coping", "awkward"]},
    {"caption": "Is this a pigeon", "image": "is_this_a_pigeon.png", "context_tags": ["confused", "misunderstanding"]},
    {"caption": "Laughing Leo", "image": "laughing_leo.png", "context_tags": ["mockery", "funny"]},
    {"caption": "Leo Cheers", "image": "leo_cheers.png", "context_tags": ["approval", "celebration"]},
    {"caption": "Monkey puppet sideways", "image": "monkey_puppet_sideways.png", "context_tags": ["awkward", "avoidance"]},
    {"caption": "Obama Medal", "image": "obama_medal.png", "context_tags": ["self-congratulation", "approval"]},
    {"caption": "Oh yeah oh no", "image": "ohyeah_ohno.png", "context_tags": ["realization", "panic"]},
    {"caption": "One does not simply", "image": "one_does_not_simply.png", "context_tags": ["challenge", "mockery"]},
    {"caption": "Panik Kalm Panik", "image": "panik_kalm_panik.png", "context_tags": ["anxiety", "doom"]},
    {"caption": "Passionate Pepe", "image": "passionate_pepe.png", "context_tags": ["serious", "inspiration"]},
    {"caption": "Roll Safe think", "image": "roll_safe_think_about_it.png", "context_tags": ["clever", "mock-agreement"]},
    {"caption": "Sad Escobar", "image": "sad_escobar.png", "context_tags": ["lonely", "sad"]},
    {"caption": "Scumbag Steve", "image": "scumbag_steve.png", "context_tags": ["bad-intentions", "annoyance"]},
    {"caption": "Scroll of truth", "image": "the_scroll_of_truth.png", "context_tags": ["truth", "sarcasm"]},
    {"caption": "Success Kid", "image": "success_kid.png", "context_tags": ["victory", "achievement"]},
    {"caption": "Surprised Pikachu", "image": "surprised_pikachu.png", "context_tags": ["shock", "obvious"]},
    {"caption": "The Office same picture", "image": "theoffice_samepicture_pam.png", "context_tags": ["obvious", "comparison"]},
    {"caption": "The Rock driving meme", "image": "the_rock_driving.png", "context_tags": ["awkward", "surprise"]},
    {"caption": "Thinking of other woman", "image": "thinking_of_other_woman.png", "context_tags": ["distraction", "awkward"]},
    {"caption": "Third world skeptical kid", "image": "third_world_skeptical_kid.png", "context_tags": ["doubt", "mockery"]},
    {"caption": "Toy Story X everywhere", "image": "toystory_x_everywhere.png", "context_tags": ["exaggeration", "ubiquity"]},
]
meme_examples += [
    {"caption": "Third world skeptical kid v2", "image": "third_world_skeptical_kid_v2.png", "context_tags": ["mockery", "doubt"]},
    {"caption": "Thinking face emoji", "image": "thinking_face.png", "context_tags": ["thinking", "unsure"]},
    {"caption": "This is fine dog", "image": "this_is_fine.png", "context_tags": ["coping", "doom"]},
    {"caption": "Two buttons dilemma", "image": "two_buttons.png", "context_tags": ["conflict", "choice"]},
    {"caption": "UNO draw 25", "image": "uno_draw25.png", "context_tags": ["defiance", "challenge"]},
    {"caption": "UNO Reverse", "image": "uno_reverse.png", "context_tags": ["reversal", "gotcha"]},
    {"caption": "Woman yelling at cat", "image": "woman_yelling_cat.png", "context_tags": ["argument", "mockery"]},
    {"caption": "Who killed Hannibal", "image": "who_killed_hannibal.png", "context_tags": ["blame-shift", "denial"]},
    {"caption": "You weren't supposed", "image": "you_werent_supposed.png", "context_tags": ["caught-in-the-act", "rule-break"]},
    {"caption": "Buff Doge vs Cheems", "image": "buffdoge_vs_cheems.png", "context_tags": ["comparison", "contrast"]},
    {"caption": "Bernie asking again", "image": "bernie_asking.png", "context_tags": ["persistence", "request"]},
    {"caption": "Epic handshake", "image": "spic_handshake.png", "context_tags": ["agreement", "collaboration"]},
    {"caption": "Roll Safe think", "image": "roll_safe_think_about_it.png", "context_tags": ["clever", "mock-agreement"]},
    {"caption": "Grus Plan", "image": "grus_plan.png", "context_tags": ["unexpected", "twist"]},
    {"caption": "Laughing Leo", "image": "laughing_leo.png", "context_tags": ["mockery", "funny"]},
    {"caption": "Batman slaps Robin", "image": "batman_slap_robin.png", "context_tags": ["shut-down", "rejection"]},
    {"caption": "Obama Medal", "image": "obama_medal.png", "context_tags": ["self-congratulation", "approval"]},
    {"caption": "Sad Escobar", "image": "sad_escobar.png", "context_tags": ["sadness", "lonely"]},
    {"caption": "Scroll of truth", "image": "the_scroll_of_truth.png", "context_tags": ["truth", "sarcasm"]},
    {"caption": "Applying clown makeup", "image": "applying_clown_makeup.png", "context_tags": ["bad-decision", "self-mockery"]},
    {"caption": "The Office same picture", "image": "theoffice_samepicture_pam.png", "context_tags": ["comparison", "obvious"]},
    {"caption": "Hide the pain Harold", "image": "hide_the_pain_harold.png", "context_tags": ["coping", "awkward"]},
    {"caption": "One does not simply", "image": "one_does_not_simply.png", "context_tags": ["challenge", "mockery"]},
    {"caption": "Expanding brain", "image": "expanding_brain.png", "context_tags": ["evolution", "satirical-smart"]},
    {"caption": "Passionate Pepe", "image": "passionate_pepe.png", "context_tags": ["inspiration", "serious"]},
    {"caption": "Fairly oddparents trophy", "image": "fairlyoddparents_trophy.png", "context_tags": ["mock-award", "sarcasm"]},
    {"caption": "Panik Kalm Panik", "image": "panik_kalm_panik.png", "context_tags": ["anxiety", "panic"]},
    {"caption": "Bike fall", "image": "bike_fall.png", "context_tags": ["self-sabotage", "bad-decision"]},
    {"caption": "Surprised Pikachu", "image": "surprised_pikachu.png", "context_tags": ["shock", "obvious"]},
    {"caption": "Change my mind", "image": "change_my_mind.png", "context_tags": ["debate", "opinion"]},
    {"caption": "Ancient aliens", "image": "ancient_aliens.png", "context_tags": ["conspiracy", "wild-idea"]},
    {"caption": "Bugs No", "image": "bugs_no.png", "context_tags": ["rejection", "denial"]},
    {"caption": "Success Kid", "image": "success_kid.png", "context_tags": ["victory", "achievement"]},
    {"caption": "Thinking face emoji", "image": "thinking_face.png", "context_tags": ["pondering", "uncertain"]},
    {"caption": "Monkey puppet sideways", "image": "monkey_puppet_sideways.png", "context_tags": ["awkward", "avoidance"]},
    {"caption": "Always has been", "image": "always_has_been.png", "context_tags": ["reveal", "gotcha"]},
    {"caption": "UNO draw 25", "image": "uno_draw25.png", "context_tags": ["defiance", "challenge"]},
    {"caption": "Gigachad", "image": "gigachad.png", "context_tags": ["confidence", "victory"]},
    {"caption": "Futurama Fry", "image": "futurama_fry.png", "context_tags": ["skeptical", "uncertain"]},
]
meme_examples += [
    {"caption": "Third world skeptical kid v2", "image": "third_world_skeptical_kid_v2.png", "context_tags": ["mockery", "doubt"]},
    {"caption": "Thinking face emoji", "image": "thinking_face.png", "context_tags": ["thinking", "unsure"]},
    {"caption": "This is fine dog", "image": "this_is_fine.png", "context_tags": ["coping", "doom"]},
    {"caption": "Two buttons dilemma", "image": "two_buttons.png", "context_tags": ["conflict", "choice"]},
    {"caption": "UNO draw 25", "image": "uno_draw25.png", "context_tags": ["defiance", "challenge"]},
    {"caption": "UNO Reverse", "image": "uno_reverse.png", "context_tags": ["reversal", "gotcha"]},
    {"caption": "Woman yelling at cat", "image": "woman_yelling_cat.png", "context_tags": ["argument", "mockery"]},
    {"caption": "Who killed Hannibal", "image": "who_killed_hannibal.png", "context_tags": ["blame-shift", "denial"]},
    {"caption": "You weren't supposed", "image": "you_werent_supposed.png", "context_tags": ["caught-in-the-act", "rule-break"]},
    {"caption": "Buff Doge vs Cheems", "image": "buffdoge_vs_cheems.png", "context_tags": ["comparison", "contrast"]},
    {"caption": "Bernie asking again", "image": "bernie_asking.png", "context_tags": ["persistence", "request"]},
    {"caption": "Epic handshake", "image": "spic_handshake.png", "context_tags": ["agreement", "collaboration"]},
    {"caption": "Roll Safe think", "image": "roll_safe_think_about_it.png", "context_tags": ["clever", "mock-agreement"]},
    {"caption": "Grus Plan", "image": "grus_plan.png", "context_tags": ["unexpected", "twist"]},
    {"caption": "Laughing Leo", "image": "laughing_leo.png", "context_tags": ["mockery", "funny"]},
    {"caption": "Batman slaps Robin", "image": "batman_slap_robin.png", "context_tags": ["shut-down", "rejection"]},
    {"caption": "Obama Medal", "image": "obama_medal.png", "context_tags": ["self-congratulation", "approval"]},
    {"caption": "Sad Escobar", "image": "sad_escobar.png", "context_tags": ["sadness", "lonely"]},
    {"caption": "Scroll of truth", "image": "the_scroll_of_truth.png", "context_tags": ["truth", "sarcasm"]},
    {"caption": "Applying clown makeup", "image": "applying_clown_makeup.png", "context_tags": ["bad-decision", "self-mockery"]},
    {"caption": "The Office same picture", "image": "theoffice_samepicture_pam.png", "context_tags": ["comparison", "obvious"]},
    {"caption": "Hide the pain Harold", "image": "hide_the_pain_harold.png", "context_tags": ["coping", "awkward"]},
    {"caption": "One does not simply", "image": "one_does_not_simply.png", "context_tags": ["challenge", "mockery"]},
    {"caption": "Expanding brain", "image": "expanding_brain.png", "context_tags": ["evolution", "satirical-smart"]},
    {"caption": "Passionate Pepe", "image": "passionate_pepe.png", "context_tags": ["inspiration", "serious"]},
    {"caption": "Fairly oddparents trophy", "image": "fairlyoddparents_trophy.png", "context_tags": ["mock-award", "sarcasm"]},
    {"caption": "Panik Kalm Panik", "image": "panik_kalm_panik.png", "context_tags": ["anxiety", "panic"]},
    {"caption": "Bike fall", "image": "bike_fall.png", "context_tags": ["self-sabotage", "bad-decision"]},
    {"caption": "Surprised Pikachu", "image": "surprised_pikachu.png", "context_tags": ["shock", "obvious"]},
    {"caption": "Change my mind", "image": "change_my_mind.png", "context_tags": ["debate", "opinion"]},
    {"caption": "Ancient aliens", "image": "ancient_aliens.png", "context_tags": ["conspiracy", "wild-idea"]},
    {"caption": "Bugs No", "image": "bugs_no.png", "context_tags": ["rejection", "denial"]},
    {"caption": "Success Kid", "image": "success_kid.png", "context_tags": ["victory", "achievement"]},
    {"caption": "Thinking face emoji", "image": "thinking_face.png", "context_tags": ["pondering", "uncertain"]},
    {"caption": "Monkey puppet sideways", "image": "monkey_puppet_sideways.png", "context_tags": ["awkward", "avoidance"]},
    {"caption": "Always has been", "image": "always_has_been.png", "context_tags": ["reveal", "gotcha"]},
    {"caption": "UNO draw 25", "image": "uno_draw25.png", "context_tags": ["defiance", "challenge"]},
    {"caption": "Gigachad", "image": "gigachad.png", "context_tags": ["confidence", "victory"]},
    {"caption": "Futurama Fry", "image": "futurama_fry.png", "context_tags": ["skeptical", "uncertain"]},
]
meme_examples += [
    {"caption": "Toy Story X everywhere", "image": "toystory_x_everywhere.png", "context_tags": ["exaggeration", "ubiquity"]},
    {"caption": "Third world skeptical kid v2", "image": "third_world_skeptical_kid_v2.png", "context_tags": ["mockery", "doubt"]},
    {"caption": "The Rock driving meme", "image": "the_rock_driving.png", "context_tags": ["awkward", "surprise"]},
    {"caption": "Thinking face emoji", "image": "thinking_face.png", "context_tags": ["pondering", "uncertain"]},
    {"caption": "Third world skeptical kid", "image": "third_world_skeptical_kid.png", "context_tags": ["doubt", "mockery"]},
    {"caption": "Third world skeptical kid v2", "image": "third_world_skeptical_kid_v2.png", "context_tags": ["mockery", "doubt"]},
    {"caption": "Sad Escobar", "image": "sad_escobar.png", "context_tags": ["lonely", "sad"]},
    {"caption": "You weren't supposed", "image": "you_werent_supposed.png", "context_tags": ["caught-in-the-act", "rule-break"]},
    {"caption": "Woman yelling at cat", "image": "woman_yelling_cat.png", "context_tags": ["argument", "mockery"]},
    {"caption": "UNO Reverse", "image": "uno_reverse.png", "context_tags": ["reversal", "gotcha"]},
    {"caption": "UNO draw 25", "image": "uno_draw25.png", "context_tags": ["defiance", "challenge"]},
    {"caption": "Two buttons dilemma", "image": "two_buttons.png", "context_tags": ["conflict", "choice"]},
    {"caption": "Scroll of truth", "image": "the_scroll_of_truth.png", "context_tags": ["truth", "sarcasm"]},
    {"caption": "Surprised Pikachu", "image": "surprised_pikachu.png", "context_tags": ["shock", "obvious"]},
    {"caption": "Sad Escobar", "image": "sad_escobar.png", "context_tags": ["lonely", "sad"]},
    {"caption": "Roll Safe think", "image": "roll_safe_think_about_it.png", "context_tags": ["clever", "mock-agreement"]},
    {"caption": "Passionate Pepe", "image": "passionate_pepe.png", "context_tags": ["serious", "inspiration"]},
    {"caption": "Panik Kalm Panik", "image": "panik_kalm_panik.png", "context_tags": ["anxiety", "panic"]},
    {"caption": "Obama Medal", "image": "obama_medal.png", "context_tags": ["self-congratulation", "approval"]},
    {"caption": "Monkey puppet sideways", "image": "monkey_puppet_sideways.png", "context_tags": ["awkward", "avoidance"]},
    {"caption": "Leo Cheers", "image": "leo_cheers.png", "context_tags": ["approval", "celebration"]},
    {"caption": "Laughing Leo", "image": "laughing_leo.png", "context_tags": ["mockery", "funny"]},
    {"caption": "Hide the pain Harold", "image": "hide_the_pain_harold.png", "context_tags": ["coping", "awkward"]},
    {"caption": "Grus Plan", "image": "grus_plan.png", "context_tags": ["unexpected", "twist"]},
    {"caption": "Gigachad", "image": "gigachad.png", "context_tags": ["confidence", "victory"]},
    {"caption": "Futurama Fry", "image": "futurama_fry.png", "context_tags": ["skeptical", "uncertain"]},
    {"caption": "Fairly oddparents trophy", "image": "fairlyoddparents_trophy.png", "context_tags": ["mock-award", "sarcasm"]},
    {"caption": "Expanding brain", "image": "expanding_brain.png", "context_tags": ["evolution", "satirical-smart"]},
    {"caption": "Evil Kermit", "image": "evil_kermit.png", "context_tags": ["temptation", "bad-advice"]},
    {"caption": "Drake Yes/No", "image": "drake_yesno.png", "context_tags": ["preference", "choice"]},
    {"caption": "Change my mind", "image": "change_my_mind.png", "context_tags": ["debate", "opinion"]},
    {"caption": "Boardroom suggestion", "image": "boardroom_meeting_suggestion.png", "context_tags": ["bad-idea", "dismissal"]},
    {"caption": "Batman slaps Robin", "image": "batman_slap_robin.png", "context_tags": ["shut-down", "rejection"]},
    {"caption": "Applying clown makeup", "image": "applying_clown_makeup.png", "context_tags": ["self-deprecation", "bad-choice"]},
]
